version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
    - 8080:80
    volumes:
    - ./:/usr/src/app
    - ./resources/volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  php:
    build:
      context: .
      dockerfile: ./resources/docker/php/Dockerfile
    volumes:
    - ./:/usr/src/app
    env_file: .env
    depends_on:
    - mysql
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.host.internal
      PHP_IDE_CONFIG: serverName=DockerCli
      COMPOSER_DISABLE_XDEBUG_WARN: "1"
      COMPOSER_ALLOW_SUPERUSER: "1"

  mysql:
    image: percona:latest
    ports:
    - 33061:3306
    command: --init-file /usr/src/mysql/guestbook.sql
    volumes:
    - ./resources/volumes/mysql/guestbook.sql:/usr/src/mysql/guestbook.sql
    env_file: .env

